### ISSUE TITLE
Не указана публичная лицензия

### ISSUE THREAD

**Issue by iEvgeny** [kuznetsovin/go_tachograph_card#2]
Приветствую!
Как я понимаю, если для проекта не указана публичная лицензия, то он распространяется под исключительными правами автора, которые в общем случае не позволяют вносить какие-либо изменения.
Это может быть простой формальностью, но мне хотелось бы немного доработать проект под собственные нужды и опубликовать измененный код. Не могли бы вы уточнить лицензию под которой распространяется код в данном репозитории?

**Comment by kuznetsovin** [comment]
Приветствую. 
Проект распространяется под лицензией MIT.
